In [24]:
import pandas as pd
import numpy as np
import sklearn as skl
import matplotlib.pyplot as plt

$\text{Data Cleaning and Pre-Processing}$

In [25]:
orgData = pd.read_csv('diabetes.csv')
orgData

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [26]:
orgData = orgData.drop(columns=orgData.columns[[8]])
orgData

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63
764,2,122,70,27,0,36.8,0.340,27
765,5,121,72,23,112,26.2,0.245,30
766,1,126,60,0,0,30.1,0.349,47
767,1,93,70,31,0,30.4,0.315,23

In [27]:
db = pd.DataFrame(data = orgData)
db = db.iloc[:,[0,1,2,3,5,6,7,4]]
db

,Pregnancies,Glucose,BloodPressure,SkinThickness,BMI,DiabetesPedigreeFunction,Age,Insulin
0,6,148,72,35,33.6,0.627,50,0
1,1,85,66,29,26.6,0.351,31,0
2,8,183,64,0,23.3,0.672,32,0
3,1,89,66,23,28.1,0.167,21,94
4,0,137,40,35,43.1,2.288,33,168
...,...,...,...,...,...,...,...,...
763,10,101,76,48,32.9,0.171,63,180
764,2,122,70,27,36.8,0.340,27,0
765,5,121,72,23,26.2,0.245,30,112
766,1,126,60,0,30.1,0.349,47,0
767,1,93,70,31,30.4,0.315,23,0

In [36]:
X,Y = db.iloc[:,[0,1,2,3,4,5,6]].to_numpy().reshape(-1, 7),db['Insulin'].to_numpy().reshape(-1, 1)
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [38]:
Y

array([[  0],
       [  0],
       [  0],
       [ 94],
       [168],
       [  0],
       [ 88],
       [  0],
       [543],
       [  0],
       [  0],
       [  0],
       [  0],
       [846],
       [175],
       [  0],
       [230],
       [  0],
       [ 83],
       [ 96],
       [235],
       [  0],
       [  0],
       [  0],
       [146],
       [115],
       [  0],
       [140],
       [110],
       [  0],
       [  0],
       [245],
       [ 54],
       [  0],
       [  0],
       [192],
       [  0],
       [  0],
       [  0],
       [207],
       [ 70],
       [  0],
       [  0],
       [240],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [ 82],
       [ 36],
       [ 23],
       [300],
       [342],
       [  0],
       [304],
       [110],
       [  0],
       [142],
       [  0],
       [  0],
       [  0],
       [128],
       [  0],
       [  0],
       [  0],
       [  0],
       [ 38],
       [100],
       [ 90],
       [140],
       [  0],
       [270],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [ 71],
       [  0],
       [  0],
       [125],
       [  0],
       [ 71],
       [110],
       [  0],
       [  0],
       [176],
       [ 48],
       [  0],
       [ 64],
       [228],
       [  0],
       [ 76],
       [ 64],
       [220],
       [  0],
       [  0],
       [  0],
       [ 40],
       [  0],
       [152],
       [  0],
       [140],
       [ 18],
       [ 36],
       [135],
       [495],
       [ 37],
       [  0],
       [175],
       [  0],
       [  0],
       [  0],
       [  0],
       [ 51],
       [100],
       [  0],
       [100],
       [  0],
       [  0],
       [ 99],
       [135],
       [ 94],
       [145],
       [  0],
       [168],
       [  0],
       [225],
       [  0],
       [ 49],
       [140],
       [ 50],
       [ 92],
       [  0],
       [325],
       [  0],
       [  0],
       [ 63],
       [  0],
       [284],
       [  0],
       [  0],
       [119],
       [  0],
       [  0],
       [204],
       [  0],
       [155],
       [485],
       [  0],
       [  0],
       [ 94],
       [135],
       [ 53],
       [114],
       [  0],
       [105],
       [285],
       [  0],
       [  0],
       [156],
       [  0],
       [  0],
       [  0],
       [ 78],
       [  0],
       [130],
       [  0],
       [ 48],
       [ 55],
       [130],
       [  0],
       [130],
       [  0],
       [  0],
       [  0],
       [ 92],
       [ 23],
       [  0],
       [  0],
       [  0],
       [495],
       [ 58],
       [114],
       [160],
       [  0],
       [ 94],
       [  0],
       [  0],
       [  0],
       [210],
       [  0],
       [ 48],
       [ 99],
       [318],
       [  0],
       [  0],
       [  0],
       [ 44],
       [190],
       [  0],
       [280],
       [  0],
       [ 87],
       [  0],
       [  0],
       [  0],
       [  0],
       [130],
       [175],
       [271],
       [129],
       [120],
       [  0],
       [  0],
       [478],
       [  0],
       [  0],
       [190],
       [ 56],
       [ 32],
       [  0],
       [  0],
       [744],
       [ 53],
       [  0],
       [370],
       [ 37],
       [  0],
       [ 45],
       [  0],
       [192],
       [  0],
       [  0],
       [  0],
       [  0],
       [ 88],
       [  0],
       [176],
       [194],
       [  0],
       [  0],
       [680],
       [402],
       [  0],
       [  0],
       [  0],
       [ 55],
       [  0],
       [258],
       [  0],
       [  0],
       [  0],
       [375],
       [150],
       [130],
       [  0],
       [  0],
       [  0],
       [  0],
       [ 67],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [ 56],
       [  0],
       [ 45],
       [  0],
       [ 57],
       [  0],
       [116],
       [  0],
       [278],
       [  0],
       [122],
       [155],
       [  0],
       [  0],
       [135],
       [545],
       [220],
       [ 49],
       [ 75],
       [ 40],
       [ 74],
       [182],
       [194],
       [  0],
       [120],
       [360],
       [215],
       [184],
       [  0],
       [  0],
       [135],
       [ 42],
       [  0],
       [  0],
       [105],
       [132],
       [148],
       [180],
       [205],
       [  0],
       [148],
       [ 96],
       [ 85],
       [  0],
       [ 94],
       [ 64],
       [  0],
       [140],
       [  0],
       [231],
       [  0],
       [  0],
       [ 29],
       [  0],
       [168],
       [156],
       [  0],
       [120],
       [ 68],
       [  0],
       [ 52],
       [  0],
       [  0],
       [ 58],
       [255],
       [  0],
       [  0],
       [171],
       [  0],
       [105],
       [ 73],
       [  0],
       [  0],
       [  0],
       [108],
       [ 83],
       [  0],
       [ 74],
       [  0],
       [  0],
       [  0],
       [  0],
       [ 43],
       [  0],
       [  0],
       [167],
       [  0],
       [ 54],
       [249],
       [325],
       [  0],
       [  0],
       [  0],
       [293],
       [ 83],
       [  0],
       [  0],
       [ 66],
       [140],
       [465],
       [ 89],
       [ 66],
       [ 94],
       [158],
       [325],
       [ 84],
       [ 75],
       [  0],
       [ 72],
       [ 82],
       [  0],
       [182],
       [ 59],
       [110],
       [ 50],
       [  0],
       [  0],
       [285],
       [ 81],
       [196],
       [  0],
       [415],
       [ 87],
       [  0],
       [275],
       [115],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [ 88],
       [  0],
       [  0],
       [165],
       [  0],
       [  0],
       [  0],
       [579],
       [  0],
       [176],
       [310],
       [ 61],
       [167],
       [474],
       [  0],
       [  0],
       [  0],
       [115],
       [170],
       [ 76],
       [ 78],
       [  0],
       [210],
       [277],
       [  0],
       [180],
       [145],
       [180],
       [  0],
       [ 85],
       [ 60],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [ 50],
       [120],
       [  0],
       [  0],
       [ 14],
       [ 70],
       [ 92],
       [ 64],
       [ 63],
       [ 95],
       [  0],
       [210],
       [  0],
       [105],
       [  0],
       [  0],
       [ 71],
       [237],
       [ 60],
       [ 56],
       [  0],
       [ 49],
       [  0],
       [  0],
       [105],
       [ 36],
       [100],
       [  0],
       [140],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [191],
       [110],
       [ 75],
       [  0],
       [328],
       [  0],
       [ 49],
       [125],
       [  0],
       [250],
       [480],
       [265],
       [  0],
       [  0],
       [ 66],
       [  0],
       [  0],
       [122],
       [  0],
       [  0],
       [  0],
       [ 76],
       [145],
       [193],
       [ 71],
       [  0],
       [  0],
       [ 79],
       [  0],
       [  0],
       [ 90],
       [170],
       [ 76],
       [  0],
       [  0],
       [210],
       [  0],
       [  0],
       [ 86],
       [105],
       [165],
       [  0],
       [  0],
       [326],
       [ 66],
       [130],
       [  0],
       [  0],
       [  0],
       [  0],
       [ 82],
       [105],
       [188],
       [  0],
       [106],
       [  0],
       [ 65],
       [  0],
       [ 56],
       [  0],
       [  0],
       [  0],
       [210],
       [155],
       [215],
       [190],
       [  0],
       [ 56],
       [ 76],
       [225],
       [207],
       [166],
       [ 67],
       [  0],
       [  0],
       [106],
       [  0],
       [ 44],
       [115],
       [215],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [274],
       [ 77],
       [ 54],
       [  0],
       [ 88],
       [ 18],
       [126],
       [126],
       [165],
       [  0],
       [  0],
       [ 44],
       [120],
       [330],
       [ 63],
       [130],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [600],
       [  0],
       [  0],
       [  0],
       [156],
       [  0],
       [  0],
       [140],
       [  0],
       [115],
       [230],
       [185],
       [  0],
       [ 25],
       [  0],
       [120],
       [  0],
       [  0],
       [  0],
       [126],
       [  0],
       [  0],
       [293],
       [ 41],
       [272],
       [182],
       [158],
       [194],
       [321],
       [  0],
       [144],
       [  0],
       [  0],
       [ 15],
       [  0],
       [  0],
       [160],
       [  0],
       [  0],
       [115],
       [  0],
       [ 54],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [ 90],
       [  0],
       [183],
       [  0],
       [  0],
       [  0],
       [ 66],
       [ 91],
       [ 46],
       [105],
       [  0],
       [  0],
       [  0],
       [152],
       [440],
       [144],
       [159],
       [130],
       [  0],
       [100],
       [106],
       [ 77],
       [  0],
       [135],
       [540],
       [ 90],
       [200],
       [  0],
       [ 70],
       [  0],
       [  0],
       [231],
       [130],
       [  0],
       [132],
       [  0],
       [  0],
       [190],
       [100],
       [168],
       [  0],
       [ 49],
       [240],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [265],
       [ 45],
       [  0],
       [105],
       [  0],
       [  0],
       [205],
       [  0],
       [  0],
       [180],
       [180],
       [  0],
       [  0],
       [ 95],
       [125],
       [  0],
       [480],
       [125],
       [  0],
       [155],
       [  0],
       [200],
       [  0],
       [  0],
       [  0],
       [100],
       [  0],
       [  0],
       [335],
       [  0],
       [160],
       [387],
       [ 22],
       [  0],
       [291],
       [  0],
       [392],
       [185],
       [  0],
       [178],
       [  0],
       [  0],
       [200],
       [127],
       [105],
       [  0],
       [  0],
       [180],
       [  0],
       [  0],
       [  0],
       [ 79],
       [  0],
       [120],
       [165],
       [  0],
       [  0],
       [120],
       [  0],
       [160],
       [  0],
       [150],
       [ 94],
       [116],
       [  0],
       [140],
       [105],
       [  0],
       [ 57],
       [200],
       [  0],
       [  0],
       [ 74],
       [  0],
       [510],
       [  0],
       [110],
       [  0],
       [  0],
       [  0],
       [  0],
       [ 16],
       [  0],
       [  0],
       [180],
       [  0],
       [112],
       [  0],
       [  0]], dtype=int64)

$\text{Machine Learning Algorithm}$